# Generated by Django 4.1.3 on 2022-11-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Тэг')),
                ('color', models.CharField(choices=[('#0000FF', 'Синий'), ('#008000', 'Зелёный'), ('#FF0000', 'Красный'), ('#ffffff', 'Белый'), ('#FFFF00', 'Жёлтый')], max_length=254, unique=True, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(max_length=254, unique=True, verbose_name='Группа блюд')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['name'],
            },
        ),
    ]
